service: app

provider:
  name: aws
  runtime: python3.11

functions:
  app:
    handler: lambda_handler.lambda_handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: lambda_handler.app
  pythonRequirements:
    dockerizePip: non-linux